name: Issue Events
on:
  issues:
    types: [opened]

jobs:
  doing-more-things:
    name: Doing THings from issues 
    runs-on: ubuntu-latest
    steps:
      - name: output issue Information
        env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTION: ${{ github.event.action }}
        run: echo "The action '${EVENT_ACTION}' was performed against '${EVENT_NAME}'"